# Generated by Django 6.0.3 on 2026-03-29 02:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Estudante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('matricula', models.CharField(max_length=50, unique=True)),
                ('telefone_familia', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='AlertaSOS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('localizacao', models.CharField(max_length=255)),
                ('data_hora', models.DateTimeField(auto_now_add=True)),
                ('resolvido', models.BooleanField(default=False)),
                ('estudante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alertas.estudante')),
            ],
        ),
    ]
